//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phyah.Web {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Phyah.Web.Resource", typeof(Resource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Value cannot be null or empty. 的本地化字符串。
        /// </summary>
        internal static string ArgumentCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("ArgumentCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Body 的本地化字符串。
        /// </summary>
        internal static string BindingSource_Body {
            get {
                return ResourceManager.GetString("BindingSource_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The provided binding source &apos;{0}&apos; is a composite. &apos;{1}&apos; requires that the source must represent a single type of input. 的本地化字符串。
        /// </summary>
        internal static string BindingSource_CannotBeComposite {
            get {
                return ResourceManager.GetString("BindingSource_CannotBeComposite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The provided binding source &apos;{0}&apos; is a greedy data source. &apos;{1}&apos; does not support greedy data sources. 的本地化字符串。
        /// </summary>
        internal static string BindingSource_CannotBeGreedy {
            get {
                return ResourceManager.GetString("BindingSource_CannotBeGreedy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom 的本地化字符串。
        /// </summary>
        internal static string BindingSource_Custom {
            get {
                return ResourceManager.GetString("BindingSource_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Form 的本地化字符串。
        /// </summary>
        internal static string BindingSource_Form {
            get {
                return ResourceManager.GetString("BindingSource_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FormFile 的本地化字符串。
        /// </summary>
        internal static string BindingSource_FormFile {
            get {
                return ResourceManager.GetString("BindingSource_FormFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Header 的本地化字符串。
        /// </summary>
        internal static string BindingSource_Header {
            get {
                return ResourceManager.GetString("BindingSource_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ModelBinding 的本地化字符串。
        /// </summary>
        internal static string BindingSource_ModelBinding {
            get {
                return ResourceManager.GetString("BindingSource_ModelBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The provided binding source &apos;{0}&apos; is not a request-based binding source. &apos;{1}&apos; requires that the source must represent data from an HTTP request. 的本地化字符串。
        /// </summary>
        internal static string BindingSource_MustBeFromRequest {
            get {
                return ResourceManager.GetString("BindingSource_MustBeFromRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The provided binding source &apos;{0}&apos; is not a greedy data source. &apos;{1}&apos; only supports greedy data sources. 的本地化字符串。
        /// </summary>
        internal static string BindingSource_MustBeGreedy {
            get {
                return ResourceManager.GetString("BindingSource_MustBeGreedy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path 的本地化字符串。
        /// </summary>
        internal static string BindingSource_Path {
            get {
                return ResourceManager.GetString("BindingSource_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query 的本地化字符串。
        /// </summary>
        internal static string BindingSource_Query {
            get {
                return ResourceManager.GetString("BindingSource_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Services 的本地化字符串。
        /// </summary>
        internal static string BindingSource_Services {
            get {
                return ResourceManager.GetString("BindingSource_Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Special 的本地化字符串。
        /// </summary>
        internal static string BindingSource_Special {
            get {
                return ResourceManager.GetString("BindingSource_Special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The ModelMetadata property must be set before accessing this property. 的本地化字符串。
        /// </summary>
        internal static string ModelBindingContext_ModelMetadataMustBeSet {
            get {
                return ResourceManager.GetString("ModelBindingContext_ModelMetadataMustBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The maximum number of allowed model errors has been reached. 的本地化字符串。
        /// </summary>
        internal static string ModelStateDictionary_MaxModelStateErrors {
            get {
                return ResourceManager.GetString("ModelStateDictionary_MaxModelStateErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A field previously marked invalid should not be marked valid. 的本地化字符串。
        /// </summary>
        internal static string Validation_InvalidFieldCannotBeReset {
            get {
                return ResourceManager.GetString("Validation_InvalidFieldCannotBeReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A field previously marked invalid should not be marked skipped. 的本地化字符串。
        /// </summary>
        internal static string Validation_InvalidFieldCannotBeReset_ToSkipped {
            get {
                return ResourceManager.GetString("Validation_InvalidFieldCannotBeReset_ToSkipped", resourceCulture);
            }
        }
    }
}
